bookit/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bookit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', 'quick.views.home', name='home'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'home'}, name='logout'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/$', 'quick.views.profile', name='profile'),
    url(r'^create_profile/$', 'quick.views.create_profile', name='create_profile'),
    url(r'^eventbrite_api/$', 'quick.views.eventbrite_api', name='eventbrite_api'),
    url(r'^meetup_api/$', 'quick.views.meetup_api', name='meetup_api'),
    url(r'^trail_api/$', 'quick.views.trail_api', name='trail_api'),
    url(r'^bootstrap/$', 'quick.views.bootstrap', name='bootstrap'),
    url(r'^match/$', 'quick.views.matching', name='match'),
    url(r'^post_event/$', 'quick.views.post_event', name='post_event'),
    url(r'^loading/$', 'quick.views.loading', name='loading'),
    url(r'^friend_match/$', 'quick.views.group_match', name='friend_match'),
    url(r'^invite_friends/$', 'quick.views.invite_friends', name='invite_friends'),
    url(r'^add_friend/$', 'quick.views.add_friend', name='add_friend'),
    url(r'^edit_profile/$', 'quick.views.edit_profile', name='edit_profile'),
    url(r'^twillo/$', 'quick.views.twillo', name='twillo'),
    url(r'^business_match/$', 'quick.views.business_match', name='business_match'),
    url(r'^loading_business/$', 'quick.views.business_loading', name='loading_business'),






)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quick/models.py
from django.contrib.auth.models import User

from django.db import models


class Interest(models.Model):
    INTERESTS = (
        ('CAR', 'Cars'),
        ('MUSIC', 'Music'),
        ('TECHNOLOGY', 'Technology'),
        ('HIKING', 'Hiking'),
        ('BIKING', 'Biking'),
        ("TRAIL", 'Trail'),
        ('COMEDY', 'Comedy'),
        ('FOOD', 'Food'),
        ('SPORTS', 'Sports'),)
    interests = models.CharField(max_length=10, choices=INTERESTS, null=True, blank=True)


    def __unicode__(self):
        return self.interests


class Profile(models.Model):
    # oauth_token = models.CharField(max_length=300, blank=True, null=True)
    user = models.ForeignKey(User, null=True, blank=True, related_name="profile")
    zipcode = models.IntegerField(max_length=5, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    interests = models.ManyToManyField(Interest, null=True, blank=True)
    TIMEZONES = (('US/Pacific', 'US/Pacific'), ('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern')
                 , ('US/Mountain', 'US/Mountain'))
    timezone = models.CharField(max_length=15, null=True, choices=TIMEZONES, blank=True)
    business = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return self.email


class Event(models.Model):
    name = models.CharField(max_length=300, null=True, blank=True)
    INTERESTS = (
        ('CAR', 'Cars'),
        ('MUSIC', 'Music'),
        ('TECHNOLOGY', 'Technology'),
        ('HIKING', 'Hiking'),
        ('BIKING', 'Biking'),
        ("TRAIL", 'Trail'),
        ('COMEDY', 'Comedy'),
        ('FOOD', 'Food'),
        ('SPORTS', 'Sports'),)
    category = models.CharField(max_length=10, choices=INTERESTS, null=True, blank=True)
    venue = models.CharField(null=True, blank=True, max_length=200)
    description = models.TextField(max_length=8000, null=True, blank=True)
    latitude = models.FloatField(max_length=100, null=True, blank=True)
    longitude = models.FloatField(max_length=100, null=True, blank=True)
    start_time = models.CharField(max_length=50, null=True, blank=True)
    end_time = models.CharField(max_length=50, null=True, blank=True)
    picture = models.URLField(null=True, blank=True)
    event_url = models.URLField(null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True)
    start_dateTime = models.DateTimeField(null=True, blank=True)
    end_dateTime = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.name


class FreeTimes(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    free_time_start = models.CharField(max_length=50, null=True, blank=True)
    free_time_end = models.CharField(max_length=50, null=True, blank=True)
    free_time_amount = models.CharField(max_length=50, null=True, blank=True)
    previous_event = models.CharField(max_length=200, null=True, blank=True)
    free_start_dateTime = models.DateTimeField(null=True, blank=True)
    free_end_dateTime = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return "Free from {} to {}".format(self.free_time_start, self.free_time_end)


class Friend(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    email = models.CharField(max_length=6000, null=True, blank=True)

    def __unicode__(self):
        return "{} friends {}".format(self.user, self.email)

quick/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelMultipleChoiceField
from quick.models import Interest, Profile

__author__ = 'Travis'



class EmailUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': '10 Character Max'}))
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'your@gmail.com'}))
    phone = forms.CharField(max_length=12, widget=forms.TextInput(attrs={'placeholder': '415-555-1111'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "first_name", "last_name", "phone")

    def clean_username(self):
            # Since User.username is unique, this check is redundant,
            # but it sets a nicer error message than the ORM. See #13147.
            username = self.cleaned_data["username"]
            try:
                User.objects.get(username=username)
            except User.DoesNotExist:
                return username
            raise forms.ValidationError(
                self.error_messages['duplicate_username'],
                code='duplicate_username',)


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['oauth_token', 'email', 'user', 'business']

quick/views.py
# Date imports
import datetime
from dateutil import tz
from django.utils import timezone
from tzlocal import get_localzone
import dateutil.parser
from dateutil.relativedelta import relativedelta

# Django imports
from django.contrib.auth.models import User
from django.db.models import Q, Count
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.views.decorators.csrf import csrf_exempt

# Import Models/Forms
from bookit.flashtrader_directory.flashtrade import eventbrite_token, meetup_key, outdoor_key, developer_key, \
    sendgrid_key, sendgrid_login
from quick.forms import ProfileCreationForm
from quick.models import Profile, FreeTimes, Event, Friend

# Google oauth imports
from googleapiclient.discovery import build
import httplib2
from oauth2client.client import AccessTokenCredentials
from requests import get

# Other imports
import json
import sendgrid
from pyzipcode import ZipCodeDatabase

# Create your views here.
from quick.utils import sign_in_google


def home(request):
    form = ProfileCreationForm()
    if request.user.is_authenticated():
        profile2 = Profile.objects.get(user=request.user)
    else:
        profile2 = {'stuff': "styff"}
        pass
    return render(request, 'home.html', {'form': form, 'profile2': profile2 })


def profile(request):
    """User logs in through google using python social login. Once the user is logged in, google calendar information is
    pulled from there account. Records of free times are created based on the time in betweeen events"""

    calendar2 = sign_in_google(request)


    # # Loops through events and determines the time your calendar event ends, and how much time you have until your
    # # next one
    for i in range(len(calendar2['items']) - 1):
        next_start = calendar2['items'][i + 1]['start']['dateTime']
        current_end = calendar2['items'][i]['end']['dateTime']
        event = (str(calendar2['items'][i]['summary']))
        # print next_start, current_end

        # Converts unicode information from Google into datetime objects, remember to change for daylight savings
        curent_event_end_dateTime = datetime.datetime.strptime(current_end, '%Y-%m-%dT%H:%M:%S-08:00')
        next_event_start_dateTime = datetime.datetime.strptime(next_start, '%Y-%m-%dT%H:%M:%S-08:00')

        #find todays date
        current_date = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S-08:00')
        real_current = datetime.datetime.strptime(current_date, '%Y-%m-%dT%H:%M:%S-08:00')
        #only allow freetimes for the next four weeks
        if next_event_start_dateTime <= real_current + datetime.timedelta(weeks=4):

            # Currently only working with free slots greater than 3 hours
            difference = next_event_start_dateTime - curent_event_end_dateTime
            if difference >= datetime.timedelta(hours=3):

                # If freetime block is greater than 1 day, will create separate blocks of free time for each day
                if difference >= datetime.timedelta(days=1):
                    hours_added = 12
                    for j in range(difference.days):
                        if j == 0:
                            free_start_dateTime = curent_event_end_dateTime
                            free_end_dateTime = free_start_dateTime + relativedelta(hours=7)
                            free_time_start = free_start_dateTime.strftime('%Y-%m-%dT%H:%M:%S-08:00')
                            free_time_end = free_end_dateTime.strftime('%Y-%m-%dT%H:%M:%S-08:00')
                            free_time_amount = free_end_dateTime - free_start_dateTime
                        else:
                            free_start_dateTime = curent_event_end_dateTime + relativedelta(hours=hours_added)
                            free_end_dateTime = free_start_dateTime + relativedelta(hours=14)
                            free_time_start = free_start_dateTime.strftime('%Y-%m-%dT%H:%M:%S-08:00')
                            free_time_end = free_end_dateTime.strftime('%Y-%m-%dT%H:%M:%S-08:00')
                            free_time_amount = free_end_dateTime - free_start_dateTime
                        hours_added += 12
                        # print free_time_end

                        FreeTimes.objects.bulk_create({FreeTimes(
                            user=request.user,
                            free_time_start=free_time_start,
                            free_time_end=free_time_end,
                            free_time_amount=free_time_amount,
                            previous_event=event,
                            free_start_dateTime=free_start_dateTime,
                            free_end_dateTime=free_end_dateTime)}
                        )
                else:
                    FreeTimes.objects.bulk_create({FreeTimes(
                        user=request.user,
                        free_time_start=current_end,
                        free_time_end=next_start,
                        free_time_amount=difference,
                        previous_event=event,
                        free_start_dateTime=curent_event_end_dateTime,
                        free_end_dateTime=next_event_start_dateTime

                    )})
        else:
            pass

    # Deletes any duplicate free times in database for current user
    duplicate_freeTimes = FreeTimes.objects.filter(user=request.user)
    for row in duplicate_freeTimes:
        if duplicate_freeTimes.filter(free_start_dateTime=row.free_start_dateTime).count() > 1:
            row.delete()
    success = {'success': 'success'}
    return HttpResponse(json.dumps(success), content_type="application/json")


# User creates a profile that saves their current interests and location
def create_profile(request):
    # Pulls information about the user from database to save
    user_social_auth = request.user.social_auth.filter(provider='google-oauth2').first()
    # access_token = user_social_auth.extra_data['access_token']
    calID = user_social_auth.uid
    if request.method == "POST":
        form = ProfileCreationForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.email = calID
            # profile.oauth_token = access_token
            profile.user = request.user
            profile.save()
            form.save_m2m()
            return HttpResponseRedirect('/loading/')
    else:
        form = ProfileCreationForm()
    data = {'form': form}
    return render(request, 'create_profile.html', data)


"""Pulls events from eventbrite Api using information from user profile. Will search for events that match the open
times and the interests of the user"""


@csrf_exempt
def eventbrite_api(request):
    profile = Profile.objects.get(user=request.user)
    interests = profile.interests.filter(interests__in=['MUSIC', 'TECHNOLOGY', 'COMEDY', 'CAR', 'FOOD', 'SPORTS'])
    zcdb = ZipCodeDatabase()

    #geocodes users zipcode to use lat and lng in search
    zipcode = zcdb[profile.zipcode]
    free_times = FreeTimes.objects.filter(user=request.user)
    eventbrite_url = 'https://www.eventbriteapi.com/v3/events/search/?'

    # for free_time in free_times:

    # formats time to match eventbrite api
    start_time = "{}Z".format(free_times.first().free_time_start[:-6])
    end_time = "{}Z".format(free_times.last().free_time_end[:-6])
    print start_time, end_time
    for interest in interests:
        eventbrite_params = {
            "token": eventbrite_token,
            'popular': True,
            'q': str(interest.interests),
            'location.latitude': zipcode.latitude,
            'location.longitude': zipcode.longitude,
            'location.within': '40mi',
            'start_date.range_start': start_time,
            'start_date.range_end': end_time
        }
        eventbrite_resp = get(url=eventbrite_url, params=eventbrite_params)
        eventbrite_data = json.loads(eventbrite_resp.text)

        # Saves returned events to database
        for event in eventbrite_data['events']:
            formatted_start = event['start']['local'] + str('.000-08:00')

            # print formatted_start.astimezone(est)
            formatted_end = str(event['end']['local']) + str('.000-08:00')

            # print  str(str(event['start']['utc'][:-1]) + str('.000-08:00')), event['start']['utc']
            # real_format = datetime.datetime.strptime(formatted_start,'%Y-%m-%dT%H:%M:%S%f-08:00')

            # Creates a datetime object from the time returned by Api

            datetime_start = dateutil.parser.parse(event['start']['utc'])

            datetime_end = dateutil.parser.parse(event['end']['utc'])

            if event['description'] is not None:

                Event.objects.bulk_create({Event(
                    name=event['name']['text'],
                    category=interest.interests,
                    venue=event['venue']['name'],
                    description=event['description']['text'],
                    latitude=event['venue']['latitude'],
                    longitude=event['venue']['longitude'],
                    start_time=formatted_start,
                    end_time=formatted_end,
                    picture=event['logo_url'],
                    event_url=event['url'],
                    user=request.user,
                    start_dateTime=datetime_start,
                    end_dateTime=datetime_end)}
                )
            else:
                Event.objects.bulk_create({Event(
                    name=event['name']['text'],
                    category=interest.interests,
                    venue=event['venue']['name'],
                    description="No description",
                    latitude=event['venue']['latitude'],
                    longitude=event['venue']['longitude'],
                    start_time=formatted_start,

quick/templates/business_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <!--jquery files-->
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>

    <!--bootstrap js file-->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/business.js' %}"></script>

    <!--bootstrap css-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!--CSS files-->
    <link href="{% static 'css/home.css' %}" rel="stylesheet">


    {% block extraheader %}
    {% endblock extraheader %}
</head>
<body>

{% block content %}
    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content profileModal">


                <h3 class="profileHead text-center">Create Your Profile</h3>

                <div class="profileCreate">
                    <form class="profileForm" method="post" action="/create_profile/">
                        {% csrf_token %}
                        {{ form.as_p }}


                        <p><input class="btn btn-primary profileCreateBtn" type="submit" value="Submit"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

</body>

</html>

quick/templates/create_profile.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_table }}

    <input type="submit" value="Submit">
</form>
</body>
</html>

quick/templates/edit_profile.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_table }}

    <input type="submit" value="Submit">
</form>
</body>
</html>

quick/templates/friend_match.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <!--jquery files-->
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>

    <!--bootstrap js file-->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!--bootstrap css-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/match.css' %}" rel="stylesheet">
    {#    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">#}
    <link href="{% static 'css/home.css' %}" rel="stylesheet">


    <!--CSS files-->


    <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCmXQO4kik_QT8QPmzZ2_teiGUak9t1rQc">
    </script>
<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top navieBar" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">BookIt</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navBAR-Home">
                <li>

                    <a href="{% url "match" %}">Events</a>
                </li>
                <li>

                    <a href data-toggle="modal" data-target=".bs-example-modal-sm">Edit Profile</a>
                </li>
                <li>
                    <a href="{% url 'friend_match' %}">Friends</a>
                </li>
                <li>
                    <a href="#inviteFriend" data-toggle="modal" data-target=".invitedFriends-modal-sm">Invite
                        Friends</a>
                </li>
                <li>

                    <a class="mapEvents">Map it</a>

                </li>
                {% for key, values in matched.items %}

                    {% if values|length > 0 %}
                        <li>
                            <a href="#{{ key }}">{{ key| lower| capfirst }}</a>

                        </li>
                    {% endif %}
                {% endfor %}


            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>


<div class="modal fade invitedFriends-modal-sm" tabindex="-1" role="dialog" aria-labelledby="inviteSmallModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">

        <div class="modal-content inviteModal">
            <h3 class="text-center ">Invite Your Friends </h3>


            <form class="inviteForm text-center">
                <p>Separate Multiple Friends by Comma</p>

                <p><input class="friendEmail" type="text" placeholder="Enter Emails"></p>

                <p>
                    <button class="inviteSubmit btn" type="submit">Invite!</button>
                </p>
            </form>
        </div>
    </div>

</div>
<div class="container event-content">


    {% for key, values in matched.items %}
        {% if values|length > 0 %}
            <!-- Title -->
            <div class="row text-center">
                <div class="col-lg-12">
                    <h3 id="{{ key }}" class="categoryHeader">{{ key| lower| capfirst }}</h3>
                </div>
            </div>
            <!-- /.row -->
        {% endif %}

        <!-- Page Features -->
        {% if values|length > 0 %}
            {% if key !=  "BIKING" and key != "HIKING" and key != "TRAIL" %}
                <div class="row text-center {{ key }}">
                    {% for  event in values|slice:":4" %}
                        <div class="col-md-3 col-sm-6 hero-feature">
                            <div class="thumbnail">
                                <div class="caption">
                                    <h4><a href="{{ event.event_url }}"> {{ event.name }}</a></h4>

                                    <p><em>Venue: {{ event.venue }}</em></p>

                                    <h5>{{ event.start_dateTime| date:"DATE_FORMAT" }}</h5>

                                    <h5>{{ event.start_dateTime|date:'TIME_FORMAT' }}
                                        - {{ event.end_dateTime| date:"TIME_FORMAT" }}</h5>


                                </div>
                                <button class="btn btn-primary bookit" data-id="{{ event.id }}">BookIt</button>
                                <p class="bookedBtn">Booked</p>
                            </div>
                        </div>
                    {% endfor %}
                    {% if values|length > 4 %}

                        {% for  event in values|slice:"4:" %}
                            <div class="col-md-3 col-sm-6 hero-feature extra-events">
                                <div class="thumbnail">
                                    <div class="caption">
                                        <h4>{{ event.name }}</h4>

                                        <p><em>Venue: {{ event.venue }}</em></p>

                                        <h5>{{ event.start_dateTime| date:"DATE_FORMAT" }}</h5>

                                        <h5>{{ event.start_dateTime|date:'TIME_FORMAT' }}
                                            - {{ event.end_dateTime| date:"TIME_FORMAT" }}</h5>


                                        <button class="btn btn-primary bookit" data-id="{{ event.id }}">BookIt</button>

                                        <p class="bookedBtn">Booked</p>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                        <div class="row text-center">
                            <div class="col-md-12">
                                <button class="btn seeMore">More Events</button>
                            </div>

                        </div>





                    {% endif %}
                    {#        <hr>#}
                </div>

            {% else %}
                <div class="row text-center {{ key }}">
                    {% for  event in values|slice:":4" %}
                        <div class="col-md-3 col-sm-6 hero-feature">
                            <div class="thumbnail thumbnail2">
                                <div class="caption">
                                    <h4>{{ event.name }}</h4>

                                    <p><em>Venue: {{ event.venue }}</em></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% if values|length > 4 %}
                        {% for  event in values|slice:"4:" %}
                            <div class="col-md-3 col-sm-6 hero-feature extra-events">
                                <div class="thumbnail thumbnail2">
                                    <div class="caption">
                                        <h4>{{ event.name }}</h4>

                                        <p><em>Venue: {{ event.venue }}</em></p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="row text-center">
                            <div class="col-md-12">
                                <button class="btn seeMore">More Events</button>
                            </div>


                        </div>

                    {% endif %}


                </div>


            {% endif %}
            <hr>


        {% endif %}

    {% endfor %}

</div>

<div class="container map-container">
    <div class="row">
        <div class="col-lg-12">
            <section id="contact" class="map">
                <div id="map-canvas"></div>
            </section>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content profileEditModal">


            <h3 class="profileHead text-center">Edit Your Profile</h3>

            <div class="profileCreate">
                <form class="profileForm" method="post" action="/edit_profile/">
                    {% csrf_token %}
                    <p><label for="id_zipcode"></label><input id="id_zipcode" name="zipcode" type="number"
                                                              placeholder="Zipcode"/></p>

                    <p><label for="id_interests">Pick Multiple Interests:</label></p><select multiple="multiple"
                                                                                             id="id_interests"
                                                                                             name="interests">
                    <option value="1">CAR</option>
                    <option value="2">MUSIC</option>
                    <option value="3">TECHNOLOGY</option>
                    <option value="4">HIKING</option>
                    <option value="5">BIKING</option>
                    <option value="6">TRAIL</option>
                    <option value="7">COMEDY</option>
                    <option value="8">FOOD</option>
                    <option value="9">SPORTS</option>
                </select>

                    <p><input class="btn btn-primary profileCreateBtn" type="submit" value="Submit"></p>
                </form>
            </div>
        </div>
    </div>
</div>


<script>


    var geocoder;
    var lat = '';
    var lng = '';
    function codeAddress() {
        {% with user.profile.all|first as profile %}
            var zipcode = {{profile.zipcode}};
        {% endwith %}

        geocoder.geocode({'address': String(zipcode)}, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                lat = results[0].geometry.location.lat();
                lng = results[0].geometry.location.lng();

            }
            else {
                alert("geocode didnt work" + status)
            }
        });

    }

    var map;
    function initialize() {
        var mapDiv = document.getElementById('map-canvas');
        map = new google.maps.Map(mapDiv, {
            {#            center: new google.maps.LatLng(lat, lng),#}
            zoom: 16,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        google.maps.event.addListenerOnce(map, 'tilesloaded', addMarkers);

        geocoder = new google.maps.Geocoder();

        codeAddress()

    }

    function addMarkers() {
        {% for key, values in matched.items %}
            {% for event in values %}
                var point = new google.maps.LatLng({{event.latitude}}, {{event.longitude}});
                {#                var image = '{{ STATIC_PREFIX }}'+ 'checkmark.png';#}
                var marker = new google.maps.Marker({
                    position: point,
                    map: map,
                    {#                icon: image, #}
                    {#                url: 'http://172.16.0.101:8882/zone/' + {{mark.id}},#}
                    title: '{{ event.name }}'
                });
                marker['infowindow'] = new google.maps.InfoWindow({
                    content: "<h1>{{event.name}}</h1> <h5>{{ event.start_dateTime| date:"DATE_FORMAT" }}</h5><h5>{{ event.start_dateTime|date:'TIME_FORMAT' }} - {{ event.end_dateTime| date:"TIME_FORMAT" }}</h5><h5><a href={{ event.event_url }}>Event</a></h5>"
                });
                google.maps.event.addListener(marker, 'click', function () {
                    //window.location.href = this.url;
                    this['infowindow'].open(map, this);
                });
                google.maps.event.addListener(marker, 'mouseover', function () {
                    // this['infowindow'].open(map, this);
                });
                google.maps.event.addListener(marker, 'mouseout', function () {
                    // this['infowindow'].close(map, this);

                });





            {% endfor %}
        {% endfor %}

    }


    google.maps.event.addDomListener(window, 'load', initialize);
</script>

</body>
</html>